repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests/test_with_pytest.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true


