repos:
  - repo: local
    hooks:
      - id: pytest
        exclude: ^test_with_pytest.py
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true


